### ISSUE TITLE
Show preview while skill editing and creating

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_skill_cms#1172]
**Actual Behaviour**
* Currently, no preview is present.

**Expected Behaviour**
* Show preview while skill editing and creating

**Would you like to work on the issue?**
I am working on some other issues, anybody can take this up.

**Comment by Orbiter** [comment]
This requires that the skill text can be used in the `/susi/chat.json` endpoint before it is stored anywhere. Therefore this endpoint now provides with https://github.com/fossasia/susi_server/commit/11beea0bf655a4deeed3637a6c41bb2432750d4d the `instant` parameter which can be used to pass a whole skill file as raw text in LoT syntax.

Because a skill file contains newline-characters this must be done with a POST request. The
following example is using a GET request and a `\n` character to simulate this:
```
http://api.susi.ai/susi/chat.json?q=lorem ipsum&instant=lorem+ipsum\ndolor+sit+amet
```
In the POST request, do not replace newlines by `\n` characters, this was only done here to have a handy example.

So it's really simple, just pass the skill text in the `instant` parameter using POST.

**Comment by akshatnitd** [comment]
I am working on some other issues, anybody can take this up.

**Comment by akshatnitd** [comment]
This has been done.
