### ISSUE TITLE
Top bar on botbuilder page should include "Deploy"

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_skill_cms#544]
**Actual Behaviour**

"Deploy" and "Preview" buttons are separated from the top bar.

**Expected Behaviour**

These two buttons should be included in the top bar.

**Screenshots of the issue**

Current situation:
<img width="1370" alt="screen shot 2018-06-01 at 12 00 31 am" src="https://user-images.githubusercontent.com/31174685/40800845-1044367e-652f-11e8-8c15-4f1b269548bf.png">

Desired result:
<img width="795" alt="screen shot 2018-06-01 at 12 02 08 am" src="https://user-images.githubusercontent.com/31174685/40800847-145ed43a-652f-11e8-8513-8dd96e624c6d.png">

**Would you like to work on the issue?**

I'll be going out to station tomorrow early morning. It's a small bug. @hkedia321, you pointed it out earlier. Can you do it please?

**Comment by mariobehling** [comment]
The screenshot does not show the "desired result".

Please simply add "deploy" behind "analytics" in the same style as part of the process (as we did discuss in the chat).

Also I am still unclear what you expect to put into the "analytics" tab, but I leave that to later.

In the document you shared we also discussed other options, e.g. "Preview" should be part of each screen instead of a button to click. Also check out some ideas on the Google Action creation platform.

![susi botbuilder - flow of the app](https://user-images.githubusercontent.com/1583873/40855226-8e0ce088-6606-11e8-9d65-be58c547f6d7.jpg)

**Comment by mariobehling** [comment]
Where is that design implemented? It looks very different. While PRs should be manageable, they should not be too far away from the desired result neither. I merged previous PRs as work in progress, but please avoid to use this as an excuse "will do it later".

<img width="795" alt="screen shot 2018-06-01 at 12 02 08 am" src="https://user-images.githubusercontent.com/31174685/40800847-145ed43a-652f-11e8-8513-8dd96e624c6d.png">
