### ISSUE TITLE
Update rating section UI to follow playstore's approach

### ISSUE THREAD

**Issue by anshumanv** [fossasia/susi_skill_cms#869]
**Actual Behaviour**
There are UI differences, star box is not displayed, total ratings are distant from average

**Expected Behaviour**
UI should be similar

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/21009455/41899126-48265e04-7949-11e8-9855-132845463581.png)

![image](https://user-images.githubusercontent.com/21009455/41899160-6043f10e-7949-11e8-8fb6-2f310953a6ea.png)

**Would you like to work on the issue?**
Yes

**Comment by akshatnitd** [comment]
I think, we can keep the priority low, for the issue. Since, all other clients have to again implement the same to make UI consistent, which would be cumbersome. Also, the present UI was made in accordance to the Analytics dashboard as shown in the [link](https://developers.google.com/actions/distribute/directory).

**Comment by anshumanv** [comment]
Okay, let's pick this up later if changes are needed. :+1:
